### ISSUE TITLE
I have preprocessed the data. Can someone help me to train the model  ?

### ISSUE THREAD

**Issue by TanujVTU** [TanujVTU/Fligth-Fare-Prediction#1]
I have preprocessed the data. Can someone help me to train the model with a good prediction rate?

**Comment by Neeraj2212** [comment]
I would love to work on your project can you describe your problem statement  . So that I can start working on it  and please assign this issue to me .

**Comment by Tanujcbe** [comment]
Can I work on the project for hactoberfest?

**Comment by TanujVTU** [comment]
@Tanujcbe You can Proceed with the work

**Comment by TanujVTU** [comment]
@Neeraj2212  I  am building a model to predict the price of the fligth using machine learning algorithm

**Comment by Neeraj2212** [comment]
I Started working on it Will You assign it to me please

**Comment by Neeraj2212** [comment]
And one more thing that you have to provide me the data otherwise how will i work on it so please share your flight fare predictoin.xlsx

**Comment by Tanujcbe** [comment]
Yes please go ahead @Neeraj2212 
The dataset is attached in the code itself.a Google drive link will be having a dataset refer it.
If the drive link is not working I would update it within 24 hours.

**Comment by Neeraj2212** [comment]
I found that dataset on kaggle no worries

**Comment by Neeraj2212** [comment]
@Tanujcbe More preprocessing is needed in this Can i go with it because model needs more parameters.

**Comment by Neeraj2212** [comment]
#5 My pull Request is submitted

**Comment by Neeraj2212** [comment]
Please Merge my Pull Request It contain full code with proper comments and markdowns

**Comment by Neeraj2212** [comment]
Your repo is not attached with Hactoberfest Attach it please

**Comment by Neeraj2212** [comment]
add hactoberfest  & hactoberfest2020 topic in about section of your repo ;
and then please label my Pull request as hactoberfest accepted & hactoberfest please .
